### ISSUE TITLE
Error encountered while executing python run_slam_pipeline.py example_demo_session

### ISSUE THREAD

**Issue by stephonjou** [real-stanford/universal_manipulation_interface#30]
############# 05_run_calibrations ###########
Traceback (most recent call last):
  File "/home/zxlong10/ALOHA/universal_manipulation_interface/scripts_slam_pipeline/05_run_calibrations.py", line 67, in <module>
    main()
  File "/opt/anaconda3/envs/zxl_umi/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/zxl_umi/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/zxl_umi/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/zxl_umi/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zxlong10/universal_manipulation_interface/scripts_slam_pipeline/05_run_calibrations.py", line 33, in main
    assert tag_path.is_file()
AssertionError
Traceback (most recent call last):
  File "/home/zxlong10/universal_manipulation_interface/run_slam_pipeline.py", line 120, in <module>
    main()
  File "/opt/anaconda3/envs/zxl_umi/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/anaconda3/envs/zxl_umi/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/envs/zxl_umi/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/anaconda3/envs/zxl_umi/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zxlong10/universal_manipulation_interface/run_slam_pipeline.py", line 106, in main
    assert result.returncode == 0
AssertionError

**Comment by lakomchik** [comment]
@stephonjou I had the same error. It seems that an older version of opencv should be used.
In my case, installing an older version of opencv with opencv-contrib solved the problem.

`pip3 install opencv-python==4.6.0.66 `
`pip3 install opencv-contrib-python`
