### ISSUE TITLE
ModuleNotFoundError: No module named 'spnav'

### ISSUE THREAD

**Issue by mrhouse-sweet** [real-stanford/universal_manipulation_interface#53]
hi
  When I run this command “python eval_real.py --robot_config=example/eval_robots_config.yaml -i cup_wild_vit_l.ckpt -o data/eval_cup_wild_example”, there is an error prompt
Traceback (most recent call last):
  File "/home/ubuntu/universal_manipulation_interface-main/eval_real.py", line 59, in <module>
    from umi.real_world.spacemouse_shared_memory import Spacemouse
  File "/home/ubuntu/universal_manipulation_interface-main/umi/real_world/spacemouse_shared_memory.py", line 4, in <module>
    from spnav import spnav_open, spnav_poll_event, spnav_close, SpnavMotionEvent, SpnavButtonEvent
ModuleNotFoundError: No module named 'spnav'

I have tried installing SPNAV using online installation methods, but they have all failed. Is there any solution?

**Comment by mrhouse-sweet** [comment]
qqq
