### ISSUE TITLE
Cannot use 3DConnexion Spacemouse Wireless to control Franka robot arm

### ISSUE THREAD

**Issue by HZWang96** [real-stanford/universal_manipulation_interface#57]
Hi everyone,

I am using a Franka robot arm. I have tried to run `control_robot.py`, but I find that I cannot control the robot arm with the Spacemouse. I can only control the gripper to open and close using the Spacemouse buttons.

Currently L119 of `control_robot.py` causes the following error:
```
Traceback (most recent call last):
  File "/home/huishi/universal_manipulation_interface/scripts_real/control_franka.py", line 119, in main
    controller.schedule_waypoint(target_pose, 
  File "/home/huishi/universal_manipulation_interface/scripts_real/umi/real_world/franka_interpolation_controller.py", line 222, in schedule_waypoint
    self.input_queue.put(message)
  File "/home/huishi/universal_manipulation_interface/scripts_real/umi/shared_memory/shared_memory_queue.py", line 97, in put
    raise Full()
queue.Full
```
Has anyone encountered this issue before or know of a possible solution? Thank you!

**Comment by HZWang96** [comment]
Problem solved. My `robot_ip` was wrong.
