### ISSUE TITLE
Issues with Mapping and Trajectory Scaling Using GoPro13

### ISSUE THREAD

**Issue by Cxy0103** [real-stanford/universal_manipulation_interface#67]
Hello,

I encountered some issues while replicating the mapping process using GoPro13. The output mapping.csv file loses a significant number of frames, and only the last few seconds are recorded. When I use the generated trajectory to operate a robotic arm, I noticed that the trajectory scale is incorrect (e.g., I drew a large triangle with the gripper, but the generated trajectory is a small triangle). Additionally, the trajectory has a noticeable tilt angle.

When I performed the same process with GoPro9, the tilt angle issue was still present, but everything else worked as expected: the trajectory scale was correct, and the mapping.csv file was complete.

Could you help me understand what might be causing this? Is it related to the IMU? Or is GoPro13 inherently unsuitable for this project?

For GoPro13, I tested the following settings:
(2.7K, 120fps, 4:3)
(4K, 60fps, 8:7)
(1080p, 60fps, 16:9)
However, the results were consistently poor, as described above. For comparison, the original GoPro9 settings were (2.7K, 60fps, 4:3). Since GoPro13 does not support 2.7K at 60fps, I tried frame skipping to match the parameters of GoPro9, but the outcome was still unsatisfactory.

Here is my mapping.csv file and the trajectory visualization generated with Python.
[mapping_camera_trajectory.csv](https://github.com/user-attachments/files/17847389/mapping_camera_trajectory.csv)
![triangle](https://github.com/user-attachments/assets/c9fd2c5d-fc5c-4c30-ba77-397a2914a158)

I would greatly appreciate any insights or suggestions you might have.

Thank you in advance!

**Comment by Johnsonones** [comment]
我也是这个问题，丢帧，麻烦问一下你在用gopro13采数的时候运行slam脚本报错吗

**Comment by soochulYoo** [comment]
Hi @Cxy0103 , I am also using GoPro13 for this project.

Long story short, I failed too.

I tried the following settings:
(2.7K, 120fps, 4:3)
(1080p, 60fps, 16:9)

but I couldn't make it.

I searched GoPro 13 firmware supporting 4:3, 2.7k and 60 fps, but there is no firmware supporting that setting.

By the way, did you make GoPro .yaml file too with [OpenICC](https://github.com/urbste/OpenImuCameraCalibrator) ?

I think the cause is likely to be in the yaml file.

I am trying to create the yaml file fitting with GoPro13 with different settings.


Also can you show us your slam_stdout.txt?

Maybe I can compare my slam_stdout.txt with yours.

Thank you.

**Comment by Ghr0228** [comment]
> Hello,
> 
> I encountered some issues while replicating the mapping process using GoPro13. The output mapping.csv file loses a significant number of frames, and only the last few seconds are recorded. When I use the generated trajectory to operate a robotic arm, I noticed that the trajectory scale is incorrect (e.g., I drew a large triangle with the gripper, but the generated trajectory is a small triangle). Additionally, the trajectory has a noticeable tilt angle.
> 
> When I performed the same process with GoPro9, the tilt angle issue was still present, but everything else worked as expected: the trajectory scale was correct, and the mapping.csv file was complete.
> 
> Could you help me understand what might be causing this? Is it related to the IMU? Or is GoPro13 inherently unsuitable for this project?
> 
> For GoPro13, I tested the following settings: (2.7K, 120fps, 4:3) (4K, 60fps, 8:7) (1080p, 60fps, 16:9) However, the results were consistently poor, as described above. For comparison, the original GoPro9 settings were (2.7K, 60fps, 4:3). Since GoPro13 does not support 2.7K at 60fps, I tried frame skipping to match the parameters of GoPro9, but the outcome was still unsatisfactory.
> 
> Here is my mapping.csv file and the trajectory visualization generated with Python. [mapping_camera_trajectory.csv](https://github.com/user-attachments/files/17847389/mapping_camera_trajectory.csv) ![triangle](https://github.com/user-attachments/assets/c9fd2c5d-fc5c-4c30-ba77-397a2914a158)
> 
> I would greatly appreciate any insights or suggestions you might have.
> 
> Thank you in advance!

Hi,bro,I meet some question by gopro13, ############# 02_create_map ###########
Pulling docker image chicheng/orb_slam3:latest
latest: Pulling from chicheng/orb_slam3
Digest: sha256:fbf562a6707a0fe9bafb04375c4cfb7b051156c14bc1e820f3f238b9aa17744f
Status: Image is up to date for chicheng/orb_slam3:latest
docker.io/chicheng/orb_slam3:latest
CompletedProcess(args=['docker', 'run', '--rm', '--volume', '/home/yinzi/universal_manipulation_interface/train_data/demos/mapping:/data', '--volume', '/home/yinzi/universal_manipulation_interface/train_data/demos/mapping:/map', 'chicheng/orb_slam3:latest', '/ORB_SLAM3/Examples/Monocular-Inertial/gopro_slam', '--vocabulary', '/ORB_SLAM3/Vocabulary/ORBvoc.txt', '--setting', '/ORB_SLAM3/Examples/Monocular-Inertial/gopro10_maxlens_fisheye_setting_v1_720.yaml', '--input_video', '/data/raw_video.mp4', '--input_imu_json', '/data/imu_data.json', '--output_trajectory_csv', '/data/mapping_camera_trajectory.csv', '--save_map', '/map/map_atlas.osa', '--mask_img', '/data/slam_mask.png'], returncode=139)
Traceback (most recent call last):
  File "/home/yinzi/universal_manipulation_interface/run_slam_pipeline.py", line 120, in <module>
    main()
  File "/home/yinzi/.conda/envs/umi/lib/python3.9/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/home/yinzi/.conda/envs/umi/lib/python3.9/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/home/yinzi/.conda/envs/umi/lib/python3.9/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yinzi/.conda/envs/umi/lib/python3.9/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/home/yinzi/universal_manipulation_interface/run_slam_pipeline.py", line 68, in main
    assert map_path.is_file()
AssertionError     How to communicate with you? I want to know the source of the problem and how do you deal with it if you meet the same question?

**Comment by XiaoWei-i** [comment]
> Hi [@Cxy0103](https://github.com/Cxy0103) , I am also using GoPro13 for this project.
> 
> Long story short, I failed too.
> 
> I tried the following settings: (2.7K, 120fps, 4:3) (1080p, 60fps, 16:9)
> 
> but I couldn't make it.
> 
> I searched GoPro 13 firmware supporting 4:3, 2.7k and 60 fps, but there is no firmware supporting that setting.
> 
> By the way, did you make GoPro .yaml file too with [OpenICC](https://github.com/urbste/OpenImuCameraCalibrator) ?
> 
> I think the cause is likely to be in the yaml file.
> 
> I am trying to create the yaml file fitting with GoPro13 with different settings.
> 
> Also can you show us your slam_stdout.txt?
> 
> Maybe I can compare my slam_stdout.txt with yours.
> 
> Thank you.

I met the similar question, have you sovled it?
